#ifndef CONFIG_H
#define CONFIG_H


#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0X10

//IDT
#define SLOBOS_TOTAL_INTERRUPTS 512 //200h



//HEAP
//100MB heap size
#define SLOBOS_HEAP_SIZE_BYTES 104857600
#define SLOBOS_HEAP_BLOCK_SIZE 4096
#define SLOBOS_HEAP_ADDRESS 0x01000000
#define SLOBOS_HEAP_TABLE_ADDRESS 0x00007E00

//disk
#define SLOBOS_SECTOR_SIZE 512

//filesystem
#define SLOBOS_MAX_FILESYSTEMS 12
#define SLOBOS_MAX_FILE_DESCRIPTORS 512
#define SLOBOS_MAX_PATH 108

//GDT
#define SLOBOS_TOTAL_GDT_SEGMENTS 6

//Tasks/Processes

#define SLOBOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define SLOBOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define SLOBOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define SLOBOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END SLOBOS_PROGRAM_VIRTUAL_ADDRESS_START - SLOBOS_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b



#endif
